#import <Foundation/Foundation.h>
#import "DaDaPushMessagePushRequest.h"
#import "DaDaPushResult.h"
#import "DaDaPushResultOfMessageObject.h"
#import "DaDaPushResultOfMessagePushResponse.h"
#import "DaDaPushResultOfPageResponseOfMessageObject.h"
#import "DaDaPushApi.h"

/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface DaDaPushDaDaPushMessageApi: NSObject <DaDaPushApi>

extern NSString* kDaDaPushDaDaPushMessageApiErrorDomain;
extern NSInteger kDaDaPushDaDaPushMessageApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(DaDaPushApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// push Message to a Channel
/// <h2>Rate Limit:</h2><ul><li>1 request per 1s</li><li>30 request per 1m</li><li>500 request per 1h</li></ul><h2>Result code/errmsg List:</h2><ul><li>0: ok</li><li>1: server error</li><li>101: channel is exists</li><li>102: channel is not exists</li><li>103: channel token error</li><li>104: channel is not exists</li><li>105: message is not exists</li><li>204: bad request</li><li>205: permission deny</li><li>206: too many request, please after 5 minutes to try!</li><li>301: duplicate username/email</li><li>302: user is not exists</li><li>303: user password is error</li><li>304: client push token is error</li><li>305: user is disabled</li><li>306: your subscription is expired</li><li>307: user not subscribe channel</li></ul>
///
/// @param body body
/// @param xChannelToken see: https://www.dadapush.com/channel/list (optional)
/// 
///  code:200 message:"OK"
///
/// @return DaDaPushResultOfMessagePushResponse*
-(NSURLSessionTask*) createMessageWithBody: (DaDaPushMessagePushRequest*) body
    xChannelToken: (NSString*) xChannelToken
    completionHandler: (void (^)(DaDaPushResultOfMessagePushResponse* output, NSError* error)) handler;


/// delete a Channel Message
/// <h2>Rate Limit:</h2><ul><li>10 request per 1s</li><li>100 request per 1m</li><li>1000 request per 1h</li></ul><h2>Result code/errmsg List:</h2><ul><li>0: ok</li><li>1: server error</li><li>101: channel is exists</li><li>102: channel is not exists</li><li>103: channel token error</li><li>104: channel is not exists</li><li>105: message is not exists</li><li>204: bad request</li><li>205: permission deny</li><li>206: too many request, please after 5 minutes to try!</li><li>301: duplicate username/email</li><li>302: user is not exists</li><li>303: user password is error</li><li>304: client push token is error</li><li>305: user is disabled</li><li>306: your subscription is expired</li><li>307: user not subscribe channel</li></ul>
///
/// @param messageId messageId
/// @param xChannelToken see: https://www.dadapush.com/channel/list (optional)
/// 
///  code:200 message:"OK"
///
/// @return DaDaPushResult*
-(NSURLSessionTask*) deleteMessageWithMessageId: (NSNumber*) messageId
    xChannelToken: (NSString*) xChannelToken
    completionHandler: (void (^)(DaDaPushResult* output, NSError* error)) handler;


/// get a Channel Message
/// <h2>Rate Limit:</h2><ul><li>10 request per 1s</li><li>100 request per 1m</li><li>1000 request per 1h</li></ul><h2>Result code/errmsg List:</h2><ul><li>0: ok</li><li>1: server error</li><li>101: channel is exists</li><li>102: channel is not exists</li><li>103: channel token error</li><li>104: channel is not exists</li><li>105: message is not exists</li><li>204: bad request</li><li>205: permission deny</li><li>206: too many request, please after 5 minutes to try!</li><li>301: duplicate username/email</li><li>302: user is not exists</li><li>303: user password is error</li><li>304: client push token is error</li><li>305: user is disabled</li><li>306: your subscription is expired</li><li>307: user not subscribe channel</li></ul>
///
/// @param messageId messageId
/// @param xChannelToken see: https://www.dadapush.com/channel/list (optional)
/// 
///  code:200 message:"OK"
///
/// @return DaDaPushResultOfMessageObject*
-(NSURLSessionTask*) getMessageWithMessageId: (NSNumber*) messageId
    xChannelToken: (NSString*) xChannelToken
    completionHandler: (void (^)(DaDaPushResultOfMessageObject* output, NSError* error)) handler;


/// get Message List
/// <h2>Rate Limit:</h2><ul><li>1 request per 1s</li><li>45 request per 1m</li></ul><h2>Result code/errmsg List:</h2><ul><li>0: ok</li><li>1: server error</li><li>101: channel is exists</li><li>102: channel is not exists</li><li>103: channel token error</li><li>104: channel is not exists</li><li>105: message is not exists</li><li>204: bad request</li><li>205: permission deny</li><li>206: too many request, please after 5 minutes to try!</li><li>301: duplicate username/email</li><li>302: user is not exists</li><li>303: user password is error</li><li>304: client push token is error</li><li>305: user is disabled</li><li>306: your subscription is expired</li><li>307: user not subscribe channel</li></ul>
///
/// @param page greater than 1 (default to @1)
/// @param pageSize range is 1,50 (default to @10)
/// @param xChannelToken see: https://www.dadapush.com/channel/list (optional)
/// 
///  code:200 message:"OK"
///
/// @return DaDaPushResultOfPageResponseOfMessageObject*
-(NSURLSessionTask*) getMessagesWithPage: (NSNumber*) page
    pageSize: (NSNumber*) pageSize
    xChannelToken: (NSString*) xChannelToken
    completionHandler: (void (^)(DaDaPushResultOfPageResponseOfMessageObject* output, NSError* error)) handler;



@end
