#import <Foundation/Foundation.h>
#import "DaDaPushObject.h"

/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol DaDaPushAction
@end

@interface DaDaPushAction : DaDaPushObject

/* action button name 
 */
@property(nonatomic) NSString* name;
/* fix value: link 
 */
@property(nonatomic) NSString* type;
/* action url 
 */
@property(nonatomic) NSString* url;

@end
