#import <Foundation/Foundation.h>
#import "DaDaPushObject.h"

/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "DaDaPushAction.h"
@protocol DaDaPushAction;
@class DaDaPushAction;



@protocol DaDaPushMessagePushRequest
@end

@interface DaDaPushMessagePushRequest : DaDaPushObject

/* action size range is 0,3 [optional]
 */
@property(nonatomic) NSArray<DaDaPushAction>* actions;
/* message content 
 */
@property(nonatomic) NSString* content;
/* when value is false, will not send client push 
 */
@property(nonatomic) NSNumber* needPush;
/* message title 
 */
@property(nonatomic) NSString* title;

@end
