#import <Foundation/Foundation.h>
#import "DaDaPushObject.h"

/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "DaDaPushAction.h"
@protocol DaDaPushAction;
@class DaDaPushAction;



@protocol DaDaPushMessageObject
@end

@interface DaDaPushMessageObject : DaDaPushObject

/* action size range is 0,3 [optional]
 */
@property(nonatomic) NSArray<DaDaPushAction>* actions;

@property(nonatomic) NSString* channelName;

@property(nonatomic) NSString* content;

@property(nonatomic) NSString* createdAt;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* title;

@end
