#import <Foundation/Foundation.h>
#import "DaDaPushObject.h"

/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "DaDaPushMessageObject.h"
@protocol DaDaPushMessageObject;
@class DaDaPushMessageObject;



@protocol DaDaPushPageResponseOfMessageObject
@end

@interface DaDaPushPageResponseOfMessageObject : DaDaPushObject


@property(nonatomic) NSArray<DaDaPushMessageObject>* content;

@property(nonatomic) NSNumber* totalElements;

@property(nonatomic) NSNumber* totalPages;

@end
